# Generated by Django 3.1.3 on 2021-01-31 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rec.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('preference', rec.models.ChoiceArrayField(base_field=models.CharField(choices=[('food', 'food'), ('restaurant', 'restaurant'), ('cafe', 'cafe'), ('bar', 'bar'), ('store', 'store'), ('meal_takeaway', 'meal_takeaway'), ('night_club', 'night_club'), ('meal_delivery', 'meal_delivery'), ('bakery', 'bakery'), ('health', 'health'), ('beauty_salon', 'beauty_salon'), ('spa', 'spa'), ('hair_care', 'hair_care'), ('grocery_or_supermarket', 'grocery_or_supermarket'), ('liquor_store', 'liquor_store'), ('gas_station', 'gas_station'), ('home_goods_store', 'home_goods_store'), ('furniture_store', 'furniture_store'), ('convenience_store', 'convenience_store'), ('lodging', 'lodging'), ('supermarket', 'supermarket'), ('shopping_mall', 'shopping_mall'), ('art_gallery', 'art_gallery'), ('general_contractor', 'general_contractor'), ('laundry', 'laundry'), ('electronics_store', 'electronics_store'), ('clothing_store', 'clothing_store'), ('book_store', 'book_store'), ('park', 'park'), ('jewelry_store', 'jewelry_store'), ('movie_theater', 'movie_theater'), ('pharmacy', 'pharmacy'), ('department_store', 'department_store'), ('storage', 'storage'), ('tourist_attraction', 'tourist_attraction'), ('travel_agency', 'travel_agency'), ('parking', 'parking'), ('florist', 'florist'), ('church', 'church'), ('real_estate_agency', 'real_estate_agency'), ('museum', 'museum'), ('place_of_worship', 'place_of_worship'), ('car_wash', 'car_wash')], max_length=256), default=list, size=None)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('name', models.CharField(max_length=140)),
                ('business_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('stars', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review_count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('stars', models.DecimalField(decimal_places=1, max_digits=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', related_query_name='review', to='rec.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', related_query_name='review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='categories',
            field=models.ManyToManyField(to='rec.BusinessCategory'),
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', related_query_name='business', to='rec.businesscity'),
        ),
    ]
