# Generated by Django 3.1.3 on 2021-03-02 13:45

from django.db import migrations, models
import django.db.models.deletion
import rec.models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(default='NA', max_length=100)),
                ('tuesday', models.CharField(default='NA', max_length=100)),
                ('wednesday', models.CharField(default='NA', max_length=100)),
                ('thursday', models.CharField(default='NA', max_length=100)),
                ('friday', models.CharField(default='NA', max_length=100)),
                ('saturday', models.CharField(default='NA', max_length=100)),
                ('sunday', models.CharField(default='NA', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preference',
            field=rec.models.ChoiceArrayField(base_field=models.CharField(choices=[('bar', 'bar'), ('cafe', 'cafe'), ('food', 'food'), ('night_club', 'night_club'), ('restaurant', 'restaurant')], max_length=256), default=list, size=None),
        ),
        migrations.AddField(
            model_name='business',
            name='days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', related_query_name='business', to='rec.businessdays'),
        ),
    ]
