# Generated by Django 3.1.3 on 2021-01-26 13:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0002_auto_20210124_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='stars_count',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=5),
        ),
    ]
